infoForms = initFormInfo();
initEnemyInfo();
infoProjectiles = initProjInfo();
infoExplosions = initExplInfo();
infoAuras = initAuraInfo();
infoAugmentPassives = initAugmentPassives();
infoAugments = initAugmentInfo();
infoUpgrades = initUpgradeInfo();
initOnHitInfo();
initStatusEffectInfo();